POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test1",
    "author": "Zhalel",
    "url": "example1.com",
    "likes": 10,
    "userId": "69f25ddbd9e2922eff04921a"
}